### ISSUE TITLE
Example not working? I am not able to connect to other devices.

### ISSUE THREAD

**Issue by anilslabs** [sbis04/flutter_bluetooth#5] opened 2019-12-24 09:47 UTC

**Comment by sbis04** [comment] 2020-03-10 09:11
### Fixed in the newer version of the app
I have updated the project to **flutter_bluetooth_serial 0.2.2** (present in the branch: **bluetooth_0.2.x**)
Link: https://github.com/sbis04/flutter_bluetooth/tree/bluetooth_0.2.x

**Closed as completed by sbis04** 2020-03-10 09:11 UTC

**Comment by PedroRTomas** [comment] 2020-10-21 17:13
Hi,
I was right about to open another issue, but then I realize that a similar already exists.
Steps to reproduce:
git clone https://github.com/sbis04/flutter_bluetooth.git
cd flutter_bluetooth
git checkout bluetooth_0.2.x
flutter pub get
flutter run
<end_of_code_operations>
After the App is open, select a device from the DropDownList and click 'Connect'. After it, this error appears:
![image](https://user-images.githubusercontent.com/48090914/96754247-ecabc880-13c8-11eb-9d06-2c312bae065b.png)
If code is run within VS, a number of exceptions are fired, due to breakpoints policy while Debugging.
Any thoughts?
Thanks in advance!
